### ISSUE TITLE
(Request) Fade In/Out Support for Rio Vis & Removable Sections

### ISSUE THREAD

**Issue by Rayveean** [roeming/Rio_Visualizer#1]
Hello Roeming,

Great work on this. Already found a good setup for the stream! I was just wondering if this could get Fade In/Out supported for when the information shows up on the pygame window. It would look cleaner for both the user using it for information and for the broadcast watching it.

Was also wondering if we can get certain sections removable like Not having the Launch angle but keep the strikezone (See Pictures Below
![2](https://user-images.githubusercontent.com/111333067/187060496-ecbf6954-6dac-4ba5-8fb5-f14bf5ba920c.png)
![1](https://user-images.githubusercontent.com/111333067/187060498-bfcd9702-2fda-441d-aaa1-cd06446156aa.png)
)

Thank you again!
-Ravian

**Comment by roeming** [comment]
All fixed
